"""LMStudio-backed SampleJudge.

LMStudio exposes an OpenAI-compatible chat/completions endpoint at
http://localhost:1234/v1 (default). Vision-capable models (e.g. Qwen3-VL,
LLaVA, MiniCPM-V) accept images via the `image_url` content part, with the
image base64-encoded as a `data:image/...;base64,...` URL.

This judge:
  - sends one chat call per image with the prompt + a JSON-output instruction
  - strips Qwen-style <think>...</think> blocks (Thinking models include them)
  - extracts the first JSON object via regex and parses
  - normalises whatever scale the model used (0-1, 0-5, 0-10) to 0-10
  - returns SampleJudgement with .error set on parse failures
"""

from __future__ import annotations

import base64
import json
import logging
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import urllib.error
import urllib.request

from bracket.judge.base import SampleJudge, SampleJudgement

logger = logging.getLogger(__name__)


_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)
_JSON_RE = re.compile(r"\{[^{}]*?\}", re.DOTALL)


DEFAULT_PROMPT_TEMPLATE = (
    "You are evaluating an image generated by a fine-tuned text-to-image model.\n\n"
    'TEXT PROMPT GIVEN TO THE MODEL:\n"{prompt}"\n\n'
    "Score the image on three axes, each from 0 to 10:\n"
    "- prompt_adherence: how well does the image match the text prompt's content "
    "(subject, action, setting, attributes)\n"
    "- visual_quality: technical quality — sharpness, composition, anatomy, "
    "color, coherent lighting\n"
    "- artifact_free: absence of obvious AI artifacts — warped faces, malformed "
    "limbs, garbled text, duplication\n\n"
    "Respond with EXACTLY one JSON object on a single line, no other text:\n"
    '{{"prompt_adherence": <0-10>, "visual_quality": <0-10>, "artifact_free": <0-10>}}'
)


@dataclass(frozen=True)
class LMStudioJudgeConfig:
    base_url: str = "http://localhost:1234/v1"
    model: str = "qwen3-vl-8b-thinking-abliterated"
    timeout_s: float = 120.0
    # Bumped from 1024 — thinking models burn 800+ tokens on preamble
    # before the JSON, and a truncated response was the dominant
    # parse-failure mode in real sessions.
    max_tokens: int = 2048
    temperature: float = 0.0
    prompt_template: str = DEFAULT_PROMPT_TEMPLATE
    # Some models output 0-1 or 0-5; if max observed score in a parsed object
    # is <= this, we'll rescale to 0-10. Set None to disable rescaling.
    autoscale_threshold: Optional[float] = 5.0
    # OpenAI-compatible structured-output mode. LMStudio supports
    # `response_format={"type": "json_schema", ...}` and constrains the
    # underlying llama.cpp grammar to emit only valid JSON matching the
    # schema. Eliminates the "Got it, let's evaluate..." rambling that
    # caused 30-50% of judgements to fail with thinking-style models.
    # Set False if the loaded model rejects the parameter (older builds).
    use_json_schema: bool = True


class LMStudioJudge(SampleJudge):
    def __init__(self, config: Optional[LMStudioJudgeConfig] = None) -> None:
        self.config = config or LMStudioJudgeConfig()

    def _encode_image(self, image_path: Path) -> str:
        suffix = image_path.suffix.lower().lstrip(".")
        mime = "jpeg" if suffix in ("jpg", "jpeg") else suffix or "png"
        data = image_path.read_bytes()
        b64 = base64.b64encode(data).decode("ascii")
        return f"data:image/{mime};base64,{b64}"

    # JSON schema for the three required score fields. Sent to LMStudio so
    # the underlying llama.cpp grammar constrains output to a parsable
    # object — no more truncated prose preambles.
    _JUDGE_JSON_SCHEMA: dict = {
        "type": "object",
        "properties": {
            "prompt_adherence": {"type": "number", "minimum": 0, "maximum": 10},
            "visual_quality":   {"type": "number", "minimum": 0, "maximum": 10},
            "artifact_free":    {"type": "number", "minimum": 0, "maximum": 10},
        },
        "required": ["prompt_adherence", "visual_quality", "artifact_free"],
        "additionalProperties": False,
    }

    def _build_payload(self, image_data_url: str, prompt: str) -> dict:
        instruction = self.config.prompt_template.format(prompt=prompt)
        payload: dict = {
            "model": self.config.model,
            "max_tokens": self.config.max_tokens,
            "temperature": self.config.temperature,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": instruction},
                        {"type": "image_url", "image_url": {"url": image_data_url}},
                    ],
                },
            ],
        }
        if self.config.use_json_schema:
            # OpenAI-compatible structured-output spec; LMStudio applies it as
            # a llama.cpp grammar so token sampling is forced into the schema.
            payload["response_format"] = {
                "type": "json_schema",
                "json_schema": {
                    "name": "image_judgement",
                    "strict": True,
                    "schema": self._JUDGE_JSON_SCHEMA,
                },
            }
        return payload

    def _post(self, payload: dict) -> str:
        url = self.config.base_url.rstrip("/") + "/chat/completions"
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url, data=body, method="POST",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=self.config.timeout_s) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
        return raw

    @staticmethod
    def _extract_choice_text(raw_body: str) -> str:
        """OpenAI-compatible response → choices[0].message.content."""
        try:
            obj = json.loads(raw_body)
        except json.JSONDecodeError as e:
            raise ValueError(f"non-JSON response from LMStudio: {e}; body[:200]={raw_body[:200]!r}")
        choices = obj.get("choices") or []
        if not choices:
            raise ValueError(f"empty choices in response: {raw_body[:200]!r}")
        msg = choices[0].get("message") or {}
        content = msg.get("content")
        if not content:
            raise ValueError(f"no message content in response: {raw_body[:200]!r}")
        if isinstance(content, list):
            # Some servers return list-of-parts; pick the first text part
            for part in content:
                if isinstance(part, dict) and part.get("type") == "text":
                    return str(part.get("text") or "")
            return ""
        return str(content)

    @staticmethod
    def parse_scores(text: str) -> dict[str, float]:
        """Strip <think> blocks, extract first JSON object, return scores dict."""
        cleaned = _THINK_RE.sub("", text).strip()
        # Try direct parse first (model that obeys the format)
        for candidate in (cleaned, *_JSON_RE.findall(cleaned)):
            try:
                obj = json.loads(candidate)
            except json.JSONDecodeError:
                continue
            if isinstance(obj, dict):
                # Coerce string values that look numeric ("8" → 8.0)
                out: dict[str, float] = {}
                for k in ("prompt_adherence", "visual_quality", "artifact_free"):
                    if k in obj:
                        try:
                            out[k] = float(obj[k])
                        except (TypeError, ValueError):
                            continue
                if out:
                    return out
        raise ValueError(f"no JSON scores in response text: {text[:300]!r}")

    def _normalise_to_10(self, scores: dict[str, float]) -> dict[str, float]:
        if self.config.autoscale_threshold is None or not scores:
            return scores
        top = max(scores.values())
        if top <= self.config.autoscale_threshold and top > 0:
            factor = 10.0 / top if top > 0 else 1.0
            return {k: max(0.0, min(10.0, v * factor)) for k, v in scores.items()}
        # Already on a 0-10 scale (or close) — just clip
        return {k: max(0.0, min(10.0, v)) for k, v in scores.items()}

    @staticmethod
    def _resolve_lms_binary() -> Optional[str]:
        """Locate the ``lms`` CLI shipped with LMStudio.

        Resolution order:
          1. ``$BRACKET_LMS_BIN`` env var (explicit user override)
          2. ``lms`` on ``PATH`` (set by ``lms bootstrap``)
          3. Per-user install:
             ``%USERPROFILE%\\.lmstudio\\bin\\lms.exe`` (Windows) or
             ``~/.lmstudio/bin/lms`` (POSIX)

        Returns the absolute path or ``None`` if no binary is found.
        """

        override = os.environ.get("BRACKET_LMS_BIN")
        if override and Path(override).is_file():
            return override

        on_path = shutil.which("lms")
        if on_path:
            return on_path

        if os.name == "nt":
            candidate = Path.home() / ".lmstudio" / "bin" / "lms.exe"
        else:
            candidate = Path.home() / ".lmstudio" / "bin" / "lms"
        return str(candidate) if candidate.is_file() else None

    def eject(self) -> None:
        """Best-effort unload of the vision model from LMStudio.

        Frees VRAM held by the VLM so the next training subprocess can
        claim the full GPU. The previous HTTP endpoint
        (``POST /api/v0/models/unload``) was removed by LMStudio — current
        builds reject it with "Unexpected endpoint or method" and the model
        stays resident. We now call ``lms unload <identifier>`` instead,
        which is the only mechanism LMStudio still supports.

        Failures are logged and swallowed — we never want a flaky
        control-plane call to abort the orchestration loop. If ``lms`` is
        missing we log a one-line install hint so the user knows why the
        next training run might be slow.
        """

        identifier = self.config.model
        lms = self._resolve_lms_binary()
        if not lms:
            logger.warning(
                "LMStudio: 'lms' CLI not found — cannot unload %s. "
                "Install it from LMStudio settings ('Developer' tab → "
                "'Install lms CLI') or run `lms bootstrap`. The VLM will "
                "stay resident and may compete with the trainer for VRAM.",
                identifier,
            )
            return

        try:
            result = subprocess.run(  # noqa: S603 - lms binary path resolved above
                [lms, "unload", identifier],
                capture_output=True,
                text=True,
                timeout=30.0,
                check=False,
            )
        except (OSError, subprocess.TimeoutExpired) as e:
            logger.warning(
                "LMStudio eject failed for %s (continuing): %s",
                identifier, e,
            )
            return

        if result.returncode == 0:
            logger.info("LMStudio: ejected model %s via lms CLI", identifier)
            return

        # Non-zero exit. Common cases:
        #   - model not currently loaded (`lms unload` returns non-zero)
        #   - identifier didn't match the loaded handle
        # Either is recoverable; log stderr and continue.
        stderr = (result.stderr or result.stdout or "").strip()
        logger.warning(
            "LMStudio eject returned %d for %s: %s",
            result.returncode, identifier, stderr or "<no output>",
        )

    def judge_image(self, image_path: Path, prompt: str) -> SampleJudgement:
        image_path = Path(image_path)
        try:
            data_url = self._encode_image(image_path)
            payload = self._build_payload(data_url, prompt)
            raw = self._post(payload)
            text = self._extract_choice_text(raw)
            parsed = self.parse_scores(text)
            normed = self._normalise_to_10(parsed)
            pa = normed.get("prompt_adherence", 0.0)
            vq = normed.get("visual_quality", 0.0)
            af = normed.get("artifact_free", 0.0)
            overall = (pa + vq + af) / 3.0
            return SampleJudgement(
                image_path=image_path, prompt=prompt,
                prompt_adherence=pa, visual_quality=vq, artifact_free=af,
                overall=overall, raw_response=text,
            )
        except (urllib.error.URLError, TimeoutError, ValueError, OSError) as e:
            logger.warning("LMStudio judge failed for %s: %s", image_path.name, e)
            return SampleJudgement(
                image_path=image_path, prompt=prompt,
                prompt_adherence=0.0, visual_quality=0.0, artifact_free=0.0,
                overall=0.0, raw_response="", error=f"{type(e).__name__}: {e}",
            )
