"""LMStudio-backed SampleJudge.

LMStudio exposes an OpenAI-compatible chat/completions endpoint at
http://localhost:1234/v1 (default). Vision-capable models (e.g. Qwen3-VL,
LLaVA, MiniCPM-V) accept images via the `image_url` content part, with the
image base64-encoded as a `data:image/...;base64,...` URL.

This judge:
  - sends one chat call per image with the prompt + a JSON-output instruction
  - strips Qwen-style <think>...</think> blocks (Thinking models include them)
  - extracts the first JSON object via regex and parses
  - normalises whatever scale the model used (0-1, 0-5, 0-10) to 0-10
  - returns SampleJudgement with .error set on parse failures
"""

from __future__ import annotations

import base64
import json
import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import urllib.error
import urllib.request

from bracket.judge.base import SampleJudge, SampleJudgement

logger = logging.getLogger(__name__)


_THINK_RE = re.compile(r"<think>.*?</think>", re.DOTALL | re.IGNORECASE)
_JSON_RE = re.compile(r"\{[^{}]*?\}", re.DOTALL)


DEFAULT_PROMPT_TEMPLATE = (
    "You are evaluating an image generated by a fine-tuned text-to-image model.\n\n"
    'TEXT PROMPT GIVEN TO THE MODEL:\n"{prompt}"\n\n'
    "Score the image on three axes, each from 0 to 10:\n"
    "- prompt_adherence: how well does the image match the text prompt's content "
    "(subject, action, setting, attributes)\n"
    "- visual_quality: technical quality — sharpness, composition, anatomy, "
    "color, coherent lighting\n"
    "- artifact_free: absence of obvious AI artifacts — warped faces, malformed "
    "limbs, garbled text, duplication\n\n"
    "Respond with EXACTLY one JSON object on a single line, no other text:\n"
    '{{"prompt_adherence": <0-10>, "visual_quality": <0-10>, "artifact_free": <0-10>}}'
)


@dataclass(frozen=True)
class LMStudioJudgeConfig:
    base_url: str = "http://localhost:1234/v1"
    model: str = "qwen3-vl-8b-thinking-abliterated"
    timeout_s: float = 120.0
    max_tokens: int = 1024
    temperature: float = 0.0
    prompt_template: str = DEFAULT_PROMPT_TEMPLATE
    # Some models output 0-1 or 0-5; if max observed score in a parsed object
    # is <= this, we'll rescale to 0-10. Set None to disable rescaling.
    autoscale_threshold: Optional[float] = 5.0


class LMStudioJudge(SampleJudge):
    def __init__(self, config: Optional[LMStudioJudgeConfig] = None) -> None:
        self.config = config or LMStudioJudgeConfig()

    def _encode_image(self, image_path: Path) -> str:
        suffix = image_path.suffix.lower().lstrip(".")
        mime = "jpeg" if suffix in ("jpg", "jpeg") else suffix or "png"
        data = image_path.read_bytes()
        b64 = base64.b64encode(data).decode("ascii")
        return f"data:image/{mime};base64,{b64}"

    def _build_payload(self, image_data_url: str, prompt: str) -> dict:
        instruction = self.config.prompt_template.format(prompt=prompt)
        return {
            "model": self.config.model,
            "max_tokens": self.config.max_tokens,
            "temperature": self.config.temperature,
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": instruction},
                        {"type": "image_url", "image_url": {"url": image_data_url}},
                    ],
                },
            ],
        }

    def _post(self, payload: dict) -> str:
        url = self.config.base_url.rstrip("/") + "/chat/completions"
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            url, data=body, method="POST",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=self.config.timeout_s) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
        return raw

    @staticmethod
    def _extract_choice_text(raw_body: str) -> str:
        """OpenAI-compatible response → choices[0].message.content."""
        try:
            obj = json.loads(raw_body)
        except json.JSONDecodeError as e:
            raise ValueError(f"non-JSON response from LMStudio: {e}; body[:200]={raw_body[:200]!r}")
        choices = obj.get("choices") or []
        if not choices:
            raise ValueError(f"empty choices in response: {raw_body[:200]!r}")
        msg = choices[0].get("message") or {}
        content = msg.get("content")
        if not content:
            raise ValueError(f"no message content in response: {raw_body[:200]!r}")
        if isinstance(content, list):
            # Some servers return list-of-parts; pick the first text part
            for part in content:
                if isinstance(part, dict) and part.get("type") == "text":
                    return str(part.get("text") or "")
            return ""
        return str(content)

    @staticmethod
    def parse_scores(text: str) -> dict[str, float]:
        """Strip <think> blocks, extract first JSON object, return scores dict."""
        cleaned = _THINK_RE.sub("", text).strip()
        # Try direct parse first (model that obeys the format)
        for candidate in (cleaned, *_JSON_RE.findall(cleaned)):
            try:
                obj = json.loads(candidate)
            except json.JSONDecodeError:
                continue
            if isinstance(obj, dict):
                # Coerce string values that look numeric ("8" → 8.0)
                out: dict[str, float] = {}
                for k in ("prompt_adherence", "visual_quality", "artifact_free"):
                    if k in obj:
                        try:
                            out[k] = float(obj[k])
                        except (TypeError, ValueError):
                            continue
                if out:
                    return out
        raise ValueError(f"no JSON scores in response text: {text[:300]!r}")

    def _normalise_to_10(self, scores: dict[str, float]) -> dict[str, float]:
        if self.config.autoscale_threshold is None or not scores:
            return scores
        top = max(scores.values())
        if top <= self.config.autoscale_threshold and top > 0:
            factor = 10.0 / top if top > 0 else 1.0
            return {k: max(0.0, min(10.0, v * factor)) for k, v in scores.items()}
        # Already on a 0-10 scale (or close) — just clip
        return {k: max(0.0, min(10.0, v)) for k, v in scores.items()}

    def _api_v0_url(self, suffix: str) -> str:
        """Translate an OpenAI-compat base_url to LMStudio's /api/v0 root.

        base_url is typically `http://localhost:1234/v1`; LMStudio's REST
        API for model lifecycle lives at `http://localhost:1234/api/v0`.
        """
        base = self.config.base_url.rstrip("/")
        if base.endswith("/v1"):
            base = base[:-3]
        return f"{base}/api/v0{suffix}"

    def eject(self) -> None:
        """Best-effort unload of the vision model from LMStudio.

        Frees VRAM held by the VLM so the next training subprocess can
        claim the full GPU. Failures are logged and swallowed — we never
        want a flaky control-plane call to abort the orchestration loop.
        """
        try:
            url = self._api_v0_url("/models/unload")
            body = json.dumps({"identifier": self.config.model}).encode("utf-8")
            req = urllib.request.Request(
                url, data=body, method="POST",
                headers={"Content-Type": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=15.0) as resp:
                resp.read()
            logger.info("LMStudio: ejected model %s", self.config.model)
        except (urllib.error.URLError, TimeoutError, OSError) as e:
            logger.warning(
                "LMStudio eject failed for %s (continuing): %s",
                self.config.model, e,
            )

    def judge_image(self, image_path: Path, prompt: str) -> SampleJudgement:
        image_path = Path(image_path)
        try:
            data_url = self._encode_image(image_path)
            payload = self._build_payload(data_url, prompt)
            raw = self._post(payload)
            text = self._extract_choice_text(raw)
            parsed = self.parse_scores(text)
            normed = self._normalise_to_10(parsed)
            pa = normed.get("prompt_adherence", 0.0)
            vq = normed.get("visual_quality", 0.0)
            af = normed.get("artifact_free", 0.0)
            overall = (pa + vq + af) / 3.0
            return SampleJudgement(
                image_path=image_path, prompt=prompt,
                prompt_adherence=pa, visual_quality=vq, artifact_free=af,
                overall=overall, raw_response=text,
            )
        except (urllib.error.URLError, TimeoutError, ValueError, OSError) as e:
            logger.warning("LMStudio judge failed for %s: %s", image_path.name, e)
            return SampleJudgement(
                image_path=image_path, prompt=prompt,
                prompt_adherence=0.0, visual_quality=0.0, artifact_free=0.0,
                overall=0.0, raw_response="", error=f"{type(e).__name__}: {e}",
            )
